import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export const exportChartAsImage = async (
  element: HTMLElement,
  filename: string,
  format: 'png' | 'jpeg' = 'png'
): Promise<void> => {
  const canvas = await html2canvas(element, {
    backgroundColor: '#ffffff',
    scale: 2,
    useCORS: true,
    logging: false,
  });

  const link = document.createElement('a');
  link.download = `${filename}.${format}`;
  link.href = canvas.toDataURL(`image/${format}`, 1.0);
  link.click();
};

export const exportChartAsPDF = async (
  element: HTMLElement,
  filename: string,
  options?: {
    orientation?: 'portrait' | 'landscape';
    title?: string;
  }
): Promise<void> => {
  const canvas = await html2canvas(element, {
    backgroundColor: '#ffffff',
    scale: 2,
    useCORS: true,
    logging: false,
  });

  const orientation = options?.orientation || 'landscape';
  const pdf = new jsPDF(orientation === 'landscape' ? 'l' : 'p', 'mm', 'a4');
  
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Add title if provided
  if (options?.title) {
    pdf.setFontSize(16);
    pdf.text(options.title, 14, 15);
  }
  
  const imgData = canvas.toDataURL('image/png');
  const imgWidth = pageWidth - 20;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  
  const startY = options?.title ? 25 : 10;
  
  // Check if image fits on one page
  if (imgHeight + startY <= pageHeight - 10) {
    pdf.addImage(imgData, 'PNG', 10, startY, imgWidth, imgHeight);
  } else {
    // Scale down to fit
    const scaledHeight = pageHeight - startY - 10;
    const scaledWidth = (canvas.width * scaledHeight) / canvas.height;
    const xOffset = (pageWidth - scaledWidth) / 2;
    pdf.addImage(imgData, 'PNG', xOffset, startY, scaledWidth, scaledHeight);
  }
  
  // Add footer
  pdf.setFontSize(8);
  pdf.setTextColor(128);
  pdf.text(
    `Generated by Finance Tracker on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 5,
    { align: 'center' }
  );
  
  pdf.save(`${filename}.pdf`);
};

export const exportMultipleChartsAsPDF = async (
  elements: { element: HTMLElement; title: string }[],
  filename: string
): Promise<void> => {
  const pdf = new jsPDF('l', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  for (let i = 0; i < elements.length; i++) {
    if (i > 0) {
      pdf.addPage();
    }

    const { element, title } = elements[i];
    const canvas = await html2canvas(element, {
      backgroundColor: '#ffffff',
      scale: 2,
      useCORS: true,
      logging: false,
    });

    // Add title
    pdf.setFontSize(14);
    pdf.setTextColor(0);
    pdf.text(title, 14, 15);

    const imgData = canvas.toDataURL('image/png');
    const imgWidth = pageWidth - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    const maxHeight = pageHeight - 30;
    const finalHeight = Math.min(imgHeight, maxHeight);
    const finalWidth = (canvas.width * finalHeight) / canvas.height;
    const xOffset = (pageWidth - finalWidth) / 2;

    pdf.addImage(imgData, 'PNG', xOffset, 22, finalWidth, finalHeight);

    // Add page number
    pdf.setFontSize(8);
    pdf.setTextColor(128);
    pdf.text(`Page ${i + 1} of ${elements.length}`, pageWidth - 20, pageHeight - 5);
  }

  // Add cover page info
  pdf.setFontSize(8);
  pdf.text(
    `Generated by Finance Tracker on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 5,
    { align: 'center' }
  );

  pdf.save(`${filename}.pdf`);
};
